import React from "react";

export default function Learn() {
  const data = {
    kind: "youtube#video",
    videoId: "XUoXE3bmDJY",
    album: {
      album_type: "single",
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/7qG3b048QCHVRO5Pv1T5lw",
          },
          href: "https://api.spotify.com/v1/artists/7qG3b048QCHVRO5Pv1T5lw",
          id: "7qG3b048QCHVRO5Pv1T5lw",
          name: "Enrique Iglesias",
          type: "artist",
          uri: "spotify:artist:7qG3b048QCHVRO5Pv1T5lw",
        },
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/1DxLCyH42yaHKGK3cl5bvG",
          },
          href: "https://api.spotify.com/v1/artists/1DxLCyH42yaHKGK3cl5bvG",
          id: "1DxLCyH42yaHKGK3cl5bvG",
          name: "Maria Becerra",
          type: "artist",
          uri: "spotify:artist:1DxLCyH42yaHKGK3cl5bvG",
        },
      ],
      available_markets: [
        "AR",
        "AU",
        "AT",
        "BE",
        "BO",
        "BR",
        "BG",
        "CA",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DK",
        "DO",
        "DE",
        "EC",
        "EE",
        "SV",
        "FI",
        "FR",
        "GR",
        "GT",
        "HN",
        "HK",
        "HU",
        "IS",
        "IE",
        "IT",
        "LV",
        "LT",
        "LU",
        "MY",
        "MT",
        "MX",
        "NL",
        "NZ",
        "NI",
        "NO",
        "PA",
        "PY",
        "PE",
        "PH",
        "PL",
        "PT",
        "SG",
        "SK",
        "ES",
        "SE",
        "CH",
        "TW",
        "TR",
        "UY",
        "US",
        "GB",
        "AD",
        "LI",
        "MC",
        "ID",
        "JP",
        "TH",
        "VN",
        "RO",
        "IL",
        "ZA",
        "SA",
        "AE",
        "BH",
        "QA",
        "OM",
        "KW",
        "EG",
        "MA",
        "DZ",
        "TN",
        "LB",
        "JO",
        "PS",
        "IN",
        "BY",
        "KZ",
        "MD",
        "UA",
        "AL",
        "BA",
        "HR",
        "ME",
        "MK",
        "RS",
        "SI",
        "KR",
        "BD",
        "PK",
        "LK",
        "GH",
        "KE",
        "NG",
        "TZ",
        "UG",
        "AG",
        "AM",
        "BS",
        "BB",
        "BZ",
        "BT",
        "BW",
        "BF",
        "CV",
        "CW",
        "DM",
        "FJ",
        "GM",
        "GE",
        "GD",
        "GW",
        "GY",
        "HT",
        "JM",
        "KI",
        "LS",
        "LR",
        "MW",
        "MV",
        "ML",
        "MH",
        "FM",
        "NA",
        "NR",
        "NE",
        "PW",
        "PG",
        "WS",
        "SM",
        "ST",
        "SN",
        "SC",
        "SL",
        "SB",
        "KN",
        "LC",
        "VC",
        "SR",
        "TL",
        "TO",
        "TT",
        "TV",
        "VU",
        "AZ",
        "BN",
        "BI",
        "KH",
        "CM",
        "TD",
        "KM",
        "GQ",
        "SZ",
        "GA",
        "GN",
        "KG",
        "LA",
        "MO",
        "MR",
        "MN",
        "NP",
        "RW",
        "TG",
        "UZ",
        "ZW",
        "BJ",
        "MG",
        "MU",
        "MZ",
        "AO",
        "CI",
        "DJ",
        "ZM",
        "CD",
        "CG",
        "IQ",
        "LY",
        "TJ",
        "VE",
        "ET",
        "XK",
      ],
      external_urls: {
        spotify: "https://open.spotify.com/album/6qW93Zylfk7oxZ8ZzwjkL5",
      },
      href: "https://api.spotify.com/v1/albums/6qW93Zylfk7oxZ8ZzwjkL5",
      id: "6qW93Zylfk7oxZ8ZzwjkL5",
      images: [
        {
          height: 640,
          url: "https://i.scdn.co/image/ab67616d0000b2733d2a295bbc9935d3e4b5bfe5",
          width: 640,
        },
        {
          height: 300,
          url: "https://i.scdn.co/image/ab67616d00001e023d2a295bbc9935d3e4b5bfe5",
          width: 300,
        },
        {
          height: 64,
          url: "https://i.scdn.co/image/ab67616d000048513d2a295bbc9935d3e4b5bfe5",
          width: 64,
        },
      ],
      name: "ASI ES LA VIDA",
      release_date: "2023-09-28",
      release_date_precision: "day",
      total_tracks: 1,
      type: "album",
      uri: "spotify:album:6qW93Zylfk7oxZ8ZzwjkL5",
    },
    artists: [
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/7qG3b048QCHVRO5Pv1T5lw",
        },
        href: "https://api.spotify.com/v1/artists/7qG3b048QCHVRO5Pv1T5lw",
        id: "7qG3b048QCHVRO5Pv1T5lw",
        name: "Enrique Iglesias",
        type: "artist",
        uri: "spotify:artist:7qG3b048QCHVRO5Pv1T5lw",
      },
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/1DxLCyH42yaHKGK3cl5bvG",
        },
        href: "https://api.spotify.com/v1/artists/1DxLCyH42yaHKGK3cl5bvG",
        id: "1DxLCyH42yaHKGK3cl5bvG",
        name: "Maria Becerra",
        type: "artist",
        uri: "spotify:artist:1DxLCyH42yaHKGK3cl5bvG",
      },
    ],
    available_markets: [
      "AR",
      "AU",
      "AT",
      "BE",
      "BO",
      "BR",
      "BG",
      "CA",
      "CL",
      "CO",
      "CR",
      "CY",
      "CZ",
      "DK",
      "DO",
      "DE",
      "EC",
      "EE",
      "SV",
      "FI",
      "FR",
      "GR",
      "GT",
      "HN",
      "HK",
      "HU",
      "IS",
      "IE",
      "IT",
      "LV",
      "LT",
      "LU",
      "MY",
      "MT",
      "MX",
      "NL",
      "NZ",
      "NI",
      "NO",
      "PA",
      "PY",
      "PE",
      "PH",
      "PL",
      "PT",
      "SG",
      "SK",
      "ES",
      "SE",
      "CH",
      "TW",
      "TR",
      "UY",
      "US",
      "GB",
      "AD",
      "LI",
      "MC",
      "ID",
      "JP",
      "TH",
      "VN",
      "RO",
      "IL",
      "ZA",
      "SA",
      "AE",
      "BH",
      "QA",
      "OM",
      "KW",
      "EG",
      "MA",
      "DZ",
      "TN",
      "LB",
      "JO",
      "PS",
      "IN",
      "BY",
      "KZ",
      "MD",
      "UA",
      "AL",
      "BA",
      "HR",
      "ME",
      "MK",
      "RS",
      "SI",
      "KR",
      "BD",
      "PK",
      "LK",
      "GH",
      "KE",
      "NG",
      "TZ",
      "UG",
      "AG",
      "AM",
      "BS",
      "BB",
      "BZ",
      "BT",
      "BW",
      "BF",
      "CV",
      "CW",
      "DM",
      "FJ",
      "GM",
      "GE",
      "GD",
      "GW",
      "GY",
      "HT",
      "JM",
      "KI",
      "LS",
      "LR",
      "MW",
      "MV",
      "ML",
      "MH",
      "FM",
      "NA",
      "NR",
      "NE",
      "PW",
      "PG",
      "WS",
      "SM",
      "ST",
      "SN",
      "SC",
      "SL",
      "SB",
      "KN",
      "LC",
      "VC",
      "SR",
      "TL",
      "TO",
      "TT",
      "TV",
      "VU",
      "AZ",
      "BN",
      "BI",
      "KH",
      "CM",
      "TD",
      "KM",
      "GQ",
      "SZ",
      "GA",
      "GN",
      "KG",
      "LA",
      "MO",
      "MR",
      "MN",
      "NP",
      "RW",
      "TG",
      "UZ",
      "ZW",
      "BJ",
      "MG",
      "MU",
      "MZ",
      "AO",
      "CI",
      "DJ",
      "ZM",
      "CD",
      "CG",
      "IQ",
      "LY",
      "TJ",
      "VE",
      "ET",
      "XK",
    ],
    disc_number: 1,
    duration_ms: 172095,
    explicit: false,
    external_ids: {
      isrc: "USSD12300536",
    },
    external_urls: {
      spotify: "https://open.spotify.com/track/0Me3GyNuLOa1YTIxhJPyCn",
    },
    href: "https://api.spotify.com/v1/tracks/0Me3GyNuLOa1YTIxhJPyCn",
    id: "0Me3GyNuLOa1YTIxhJPyCn",
    is_local: false,
    name: "ASI ES LA VIDA",
    popularity: 83,
    preview_url:
      "https://p.scdn.co/mp3-preview/6f67d028d788a09dea00bf4d16d0e771744a942b?cid=cbc1d5accfed42718ee63df019ab2912",
    track_number: 1,
    type: "track",
    uri: "spotify:track:0Me3GyNuLOa1YTIxhJPyCn",
  };
  return (
    <div
      className="h-screen w-screen bg-black"
      style={{
        backgroundImage: `url(${data.album.images[0].url})`,
        backgroundSize: "center",
        backgroundRepeat: "no-repeat",
        backgroundPosition: "center",

        // filter: "blur(30px)",
      }}
    >
      <div className="bg-[#00000080] w-full h-full">
        <h1>Hello 123</h1>
      </div>
    </div>
  );
}
